# Generated by Django 4.0.3 on 2022-03-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='demo_time',
            field=models.CharField(max_length=255),
        ),
    ]
